# This file was generated by GoReleaser. DO NOT EDIT.
cask "doist" do
  name "doist"
  desc "doist is an unofficial command line app for interacting with the Todoist API"
  homepage "https://github.com/chaosteil/doist"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "doist"

  on_macos do
    on_intel do
      url "https://github.com/chaosteil/doist/releases/download/v#{version}/doist_#{version}_darwin_amd64.tar.gz"
      sha256 "a5c1548ded04e162ce5bfcc88773ff5e4b2125dc270932739057031a268dd8aa"
    end
    on_arm do
      url "https://github.com/chaosteil/doist/releases/download/v#{version}/doist_#{version}_darwin_arm64.tar.gz"
      sha256 "449c796e9b56e6f8eb1980b85bde43a4db538ff95b8be5e0922265eb6e8c8289"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/chaosteil/doist/releases/download/v#{version}/doist_#{version}_linux_amd64.tar.gz"
      sha256 "8e303153008a54ce55070e4df671a1c2f23bbee8f121a278619e9b674fa8ef5e"
    end
  end

  # No zap stanza required
end
